Add user and password authentication.
owncloud/search_elastic pull request #248
Opened 2022-02-09 17:32 UTC by ahherrera

Issue: https://github.com/owncloud/search_elastic/issues/246
Add user and password authentication.

2022-02-10 16:41 UTC, IljaN commented
Please ensure that CI is green :)

2022-02-11 11:28 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISE-latest-chrome-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/1929/16/1

2022-02-11 11:28 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiLimitSearches-latest-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/1929/19/1

2022-02-11 11:28 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiLimitSearches-master-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/1929/18/1

2022-02-11 13:57 UTC, ahherrera commented
@IljaN I have had problems deploying the PR. Can you tell me how to solve these problems?
![Screen Shot 2022-02-11 at 8 55 50 AM](https://user-images.githubusercontent.com/6892751/153604171-1240a987-753b-432f-8dea-c1493afb6f90.png)

2022-02-11 14:06 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISE-master-firefox-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/1930/15/1

2022-02-11 14:11 UTC, IljaN commented
Hmhh something cancels the pipeline... maybe a failing acceptance test?

2022-02-11 14:19 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISE-latest-chrome-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/1931/16/1

2022-02-11 15:40 UTC, IljaN requested changes
:+1: Just a few nitpicks. Don't merge the two parse functions if it's to complicated.

2022-02-11 15:40 UTC, IljaN commented on lib/SearchElasticConfigService.php
> +		$sets = explode('@', $serverPart);
```suggestion
		$sets = \explode('@', $serverPart);
```

2022-02-11 15:40 UTC, IljaN commented on lib/SearchElasticConfigService.php
> +		$host = explode(':', $sets[1]);
```suggestion
		$host = \explode(':', $sets[1]);
```

2022-02-11 15:40 UTC, IljaN commented on lib/SearchElasticConfigService.php
> +			if (str_contains($serverPart, '@')) {
Is it possible to eliminate this if by merging the methods ``parseServerWithUserPassAuthentication`` and ``parseServerWithoutAuthentication`` in to one?

2022-02-11 15:40 UTC, IljaN commented on lib/SearchElasticConfigService.php
> +			if (str_contains($serverPart, '@')) {
```suggestion
			if (\str_contains($serverPart, '@')) {
```

2022-02-14 02:08 UTC, ahherrera commented on lib/SearchElasticConfigService.php
> +			if (str_contains($serverPart, '@')) {
The functionality is separated into two methods in order to facilitate new types of authentication in the future without damaging existing methods. Please let me know if it is necessary to merge them.

2022-02-14 08:57 UTC, IljaN commented on lib/SearchElasticConfigService.php
> +			if (str_contains($serverPart, '@')) {
:+1:

2022-02-15 15:23 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiLimitSearches-latest-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/1944/19/1

2022-02-15 16:27 UTC, merged

2022-02-15 16:53 UTC, mmattel commented
I guess this is docs relevant, in case, can you pls file a docs issue.

@EParzefall fyi