Bugs found in release 2.1.0 fixed.
owncloud/search_elastic pull request #277
Opened 2022-03-31 12:13 UTC by ahherrera

Protocol is added and authentication settings are fixed.

2022-03-31 12:41 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiSearchElastic-latest-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/2033/20
<!-- id: pr-277 -->

2022-03-31 12:43 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUISE-master-firefox-mysql8.0-php7.4-es7.10</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/search_elastic/2034/14
<!-- id: pr-277 -->

2022-03-31 21:02 UTC, phil-davis commented
Acceptance tests fail in the setup-es step, for example https://drone.owncloud.com/owncloud/search_elastic/2038/13/12
```
+ cd /var/www/owncloud/server
+ php occ config:app:set search_elastic servers --value elasticsearch
Config value servers for app search_elastic set to elasticsearch
+ php occ search:index:reset --force

In Http.php line 186:
                                              
  Couldn't connect to host, Elasticsearch down?  
                                                
search:index:reset [-f|--force]
```

I guess that something to do with connecting to the elastic search server has changed. Does something need to be changed in the drone setup? Or is there an unintended change/bug in the code here that is not backward-compatible?

2022-04-18 00:23 UTC, ahherrera commented
@jnweiger Please check, the error has been fixed.

2022-04-19 09:12 UTC, phil-davis reviewed
Looks good, and CI is passing.

@ahherrera please mention the issue(s) that are fixed by this PR.

2022-04-19 11:39 UTC, ahherrera commented
> Looks good, and CI is passing.
> 
> @ahherrera please mention the issue(s) that are fixed by this PR.

Already added.

2022-04-19 14:10 UTC, phil-davis commented
@jnweiger I guess you can QA check gthe behavior.

Who should review this from a developer code perspective?

2022-04-24 21:14 UTC, xoxys commented
@C0rby could you do a review regarding https://github.com/owncloud/search_elastic/issues/258#issuecomment-1074035734?

2022-04-26 14:14 UTC, C0rby requested changes

2022-04-26 14:14 UTC, C0rby commented on lib/SearchElasticConfigService.php
> +		$server = [
This function should use https://www.php.net/manual/en/function.parse-url.php. This will properly handle the cases where the provided URI contains a path ending with a fragment.

2022-04-29 05:40 UTC, ahherrera commented on lib/SearchElasticConfigService.php
> +		$server = [
> This function should use https://www.php.net/manual/en/function.parse-url.php. This will properly handle the cases where the provided URI contains a path ending with a fragment.

@C0rby The url data was parsed using parse_url function.

2022-05-03 03:41 UTC, phil-davis reviewed
Looks OK to me - @C0rby please review again.

2022-05-03 12:40 UTC, C0rby commented
:+1: for using `\parse_url` but I still see some strange URLs.
When I set the URL to `localhost:9200/adsf`
Then the requests go to: `//adsfoc-ochhbgh1wscs` and `//adsf_ingest/pipeline/oc-processor-ochhbgh1wscs`.

The expected URLs are `/asdf/oc-ochhbgh1wscs` and `/adsf/_ingest/pipeline/oc-processor-ochhbgh1wscs`.

2022-05-03 12:40 UTC, C0rby submitted a review, later dismissed
See other comment ^

2022-05-03 13:14 UTC, ahherrera commented
> 👍 for using `\parse_url` but I still see some strange URLs. When I set the URL to `localhost:9200/adsf` Then the requests go to: `//adsfoc-ochhbgh1wscs` and `//adsf_ingest/pipeline/oc-processor-ochhbgh1wscs`.
> 
> The expected URLs are `/asdf/oc-ochhbgh1wscs` and `/adsf/_ingest/pipeline/oc-processor-ochhbgh1wscs`.

@C0rby  I don't understand the comment, could you please explain a little more?

2022-05-03 13:23 UTC, C0rby commented
When you configure the URL in the front-end to `localhost:9200` then the requests are not send to `localhost:9200` directly but instead the app adds other path segments like `oc-ochhbgh1wscs`. So the request goes to `localhost:9200/oc-ochhbgh1wscs`.

Now if the configured URL also contains a path like: `localhost:9200/somepath` then the requests are expected to go to `localhost:9200/somepath/oc-ochhbgh1wscs` but instead the path is not added correctly and the request goes to `localhost:9200//somepathoc-ochhbgh1wscs`

2022-05-03 13:36 UTC, ahherrera commented
> When you configure the URL in the front-end to `localhost:9200` then the requests are not send to `localhost:9200` directly but instead the app adds other path segments like `oc-ochhbgh1wscs`. So the request goes to `localhost:9200/oc-ochhbgh1wscs`.
> 
> Now if the configured URL also contains a path like: `localhost:9200/somepath` then the requests are expected to go to `localhost:9200/somepath/oc-ochhbgh1wscs` but instead the path is not added correctly and the request goes to `localhost:9200//somepathoc-ochhbgh1wscs`

I have tested on my local and have not detected what you are talking about. Please can you describe me a step by step to replicate it in my local environment. THX

2022-05-04 12:16 UTC, C0rby commented
Here are some screenshots:
![image](https://user-images.githubusercontent.com/5579653/166678991-99857820-61af-4775-9edb-15e0681dbf47.png)

Since I don't have an elastic server I just start a python http server to capture the requests.

When entering `localhost:9200/adsf` and pressing `Save Configuration` or `Setup Index`, I can see these requests:
![image](https://user-images.githubusercontent.com/5579653/166679057-f69c693d-b300-4a61-bdf6-e76b2dc645a9.png)

2022-05-11 08:18 UTC, C0rby commented
It's better now but there is still a slash missing between `/asdf` and `oc-ochhbgh1wscs`
![image](https://user-images.githubusercontent.com/5579653/167802494-f9dd81ce-9d9c-4285-9349-3419fc871d19.png)

2022-05-11 13:14 UTC, C0rby commented
> I think it is being placed internally by the elastic library being used. Can you please explain me what is the origin of this string?

Yeah I also don't exactly know where it comes from but I think a solution could be to ensure that the path always ends with a slash.

I.e. `asdf` should become `asdf/` and `asdf/` stays `asdf/` and if no path was given then it should be `/` I guess.

2022-05-12 02:08 UTC, ahherrera commented
@C0rby 
The string being concatenated is the index identifier and this process is done internally in the library being used.
This identifier is created when the index is created:
![image](https://user-images.githubusercontent.com/6892751/167977696-84d66578-243f-421b-9a43-7afebd34bbbb.png)


Could you please tell me which version of elastica if you are using to perform the tests?
I have tested with Elastic version 7.9.3 and I do not get the error when generating the index.

2022-05-12 02:15 UTC, ahherrera commented
> > I think it is being placed internally by the elastic library being used. Can you please explain me what is the origin of this string?
> 
> Yeah I also don't exactly know where it comes from but I think a solution could be to ensure that the path always ends with a slash.
> 
> I.e. `asdf` should become `asdf/` and `asdf/` stays `asdf/` and if no path was given then it should be `/` I guess.

I have tested by ending the url with the "/" and I get errors when executing the file indexing.

2022-05-18 13:06 UTC, jvillafanez commented
Things changed in https://github.com/owncloud/search_elastic/pull/277/commits/68cd36d61fdbceeb3f9dc3987a0dd7860f942eb3:
* You can still provide a list of servers using `,` as separator (maybe @butonic can provide additional information. I'm assuming it's for a cluster setup, but I'm not sure)
  * All of those server will use the same username and password if specified.
* The password will be stored in the credentials manager, so it shouldn't appear in the config report. The username will still appear as part of the app configuration (it will appear in the config report), so support should be able to guess that the connection with elasticsearch is authenticated.
* Protocol (http / https) is optional, but it will be added automatically if it isn't provided (http will be assumed).
* The servers won't be saved if a malformed url is detected.
  * It won't prevent saving wrong credentials
  * urls that are well formed but point to nowhere or invalid addresses can still be saved.

Tested:
* Http protocol is automatically added if it isn't provided.
  `10.10.10.10:9200` will be converted to `http://10.10.10.10:9200` and then saved. You'll need to reload the page to see the change.
* Https tested against a proxy. It should behave the same way with a direct https connection against elasticsearch.
* Port 443 must be explicitly added if https is used (or use a different port)
* Path tested against a proxy
  `https://server.prv:443/elastic/` will connect to the proxy, who will send the request to where elasticsearch is. Trailing `/` might be required depending on the specific setup.

To be considered:
* Add support for curl options. This might be needed in order to connect to elasticsearch with https.
  * We might need to ignore the ssl certificate, or provide a certificate to verify the connection. I've tested https by hardcoding some options. Right now, it will use the defaults, so I think the certificate should be a well-known one (maybe one from letsencrypt is good enough)
* Assume port 443 for https if none is provided. Right now, we aren't doing anything and leave the decision to the "elastica" library, which seems to use always port 80 if none is provided. Currently, the workaround is to set the port explicitly.
* Consistency while saving the settings. We might want to always save the settings even if there are malformed urls so the user is less confused about what data we're using to test the connection.

2022-05-20 12:27 UTC, jvillafanez commented
```
diff --git a/lib/SearchElasticConfigService.php b/lib/SearchElasticConfigService.php
index ee33c9e..8da40cb 100644
--- a/lib/SearchElasticConfigService.php
+++ b/lib/SearchElasticConfigService.php
@@ -259,6 +259,12 @@ class SearchElasticConfigService {
 
                        if (isset($parsedServer['scheme'])) {
                                $serverData['transport'] = $parsedServer['scheme'];
+                               if ($parsedServer['scheme'] === 'https') {
+                                       $serverData['curl'] = [
+                                               CURLOPT_SSL_VERIFYPEER => false,
+                                               CURLOPT_SSL_VERIFYHOST => false,
+                                       ];
+                               }
                        } else {
                                $serverData['transport'] = 'http';
                        }
```
Something like that will be needed if the elasticsearch certificate isn't well-known in order to disable certificate validation. Note that this isn't recommended. This isn't currently implemented and would require admin confirmation somehow (probably a checkbox in the web UI)
We could also allow the admin to provide certificates, or use the ones stored in ownCloud

2022-05-24 11:46 UTC, jvillafanez commented
> Add support for curl options. This might be needed in order to connect to elasticsearch with https. 

No changes for now. HTTPS will require valid certificates. We'll assume the certificates will need to be installed in the OS default location if needed.

> Consistency while saving the settings. We might want to always save the settings even if there are malformed urls so the user is less confused about what data we're using to test the connection.

No changes. A simple validation will happen before saving. This validation **WON'T** include connectivity against elasticsearch

2022-05-25 10:47 UTC, mmattel commented
@jvillafanez I cant identify this but you may have the answer for:
Is the API-Key version also implemented as required? see:
https://github.com/owncloud/search_elastic/issues/246#issuecomment-1028067335
https://github.com/owncloud/search_elastic/issues/246#issuecomment-1038861845
This also impacts documentation...

2022-05-25 10:59 UTC, jvillafanez commented
API-key auth isn't supported yet in this PR. I need to check how to setup elasticsearch with that.

2022-05-25 16:45 UTC, jvillafanez commented
Bringing support for API key will take some time since we need to refactor the code from this PR. I don't see a clean way to implement it otherwise. If we don't need support for API key in the short term, I think we can release this PR now to have time to plan ahead.

2022-05-27 13:25 UTC, jvillafanez commented
Support for API Key is coming. The PR already contains code which should be working. I'm adding unit tests for the functionality and I'll put the PR into review once it's finished and after manual verification of the functionality.

2022-06-09 07:07 UTC, jvillafanez commented
The PR can be reviewed now. The only missing piece is the unit test

2022-06-09 12:42 UTC, jvillafanez commented
This is ready to review.

2022-06-23 08:29 UTC, jnweiger commented
Ah cool. thanks @jvillafanez and @phil-davis -- we are ready to release with this, right?

2022-06-23 08:35 UTC, phil-davis commented
> Ah cool. thanks @jvillafanez and @phil-davis -- we are ready to release with this, right?

I am happy. It needs some technical person(s) on the review list to give a "green tick".

2022-06-23 10:12 UTC, jnweiger approved these changes
LGTM

There is one other issue, I'd like to push forward:
https://github.com/owncloud/search_elastic/issues/281

2022-06-23 10:13 UTC, merged